### ISSUE TITLE
Arabic and Spanish translations

### ISSUE THREAD

**Issue by maggie0002** [LearnersBlock/learners-block#113]
https://hosted.weblate.org/projects/learners-block/interface/es/
https://hosted.weblate.org/projects/learners-block/interface/pt_BR/

**Comment by Blask0** [comment]
I did some translations on "Interfaces"

**Comment by maggie0002** [comment]
> I did some translations on "Interfaces"

This is great, thanks!

I have committed the translations into https://github.com/LearnersBlock/learners-block/pull/117. 

Will leave this issue and the PR open as still some translations to go. :)

**Comment by fitojb** [comment]
What is the deadline?

**Comment by maggie0002** [comment]
> What is the deadline?

No particular deadline, it's going to be on a rolling basis. We are appreciative of everything we get. 

There are only 19 words left untranslated from the Interface and then we can close the ticket. Because it was so close to finished, we merged what we had and enabled the Spanish option on the interface. We can merge in the last parts when they are ready :).

**Comment by maggie0002** [comment]
There are still a handful of strings missing, but thanks to amazing contributions from the Weblate community, this is mostly now complete and merged into the repo. Going to close the issue and switch to Weblate interface for tracking.

**Comment by maggie0002** [comment]
Fallen behind a little bit on Spanish and Portuguese as we approach being ready for v1 so reopening here as reminder.

**Comment by maggie0002** [comment]
*Arabic done, Spanish a few gaps, Portuguese dropped right off.

**Comment by maggie0002** [comment]
Without the support of the Weblate community, I have no idea what we would have done. When starting the project, getting translations was the biggest concern as it is so integral to this project. Spanish and Arabic are now up to date, in addition to German, French and the beginnings of many others.

We were fortunate early on to get Portuguese contributions but haven't been so lucky of late. I was hoping to have made this one of the core languages, but think we will have to resort to this being an ongoing process. French, Arabic and Spanish were the core we initially aimed for and have managed, everything else is just a huge bonus!

Going to close this issue now as these core languages are up to date for a production release, and future minor changes can be tracked via the Weblate platform directly.
