### ISSUE TITLE
Add automated tests to interface

### ISSUE THREAD

**Issue by maximilianoertel** [LearnersBlock/learners-block#33]
Implement automated tests using @vue/test-utils (https://vue-test-utils.vuejs.org/)

**Comment by maggie0002** [comment]
For future reference: https://quasar.dev/quasar-cli/testing-and-auditing#Installing

**Comment by maggie0002** [comment]
Rough notes of test used so far manually. Left here for future reference. 

- [ ] Test hostname change on first boot and reboot
- [ ] Check database recover 
- [ ] Check hostname resolution when container and device don’t match
- [ ] Supervisor update
- [ ] Hostname
- [ ] Device reboot
- [ ] Supervisor state

- [ ] Network:
    - [x] Test hidden network
    - [x] Test username on enterprise network
    - [x] Refresh network points
    - [x] Set wifi password
    - [x] Disconnect from a network
    - [x] Connect to a network
    - [x] Captive portal check 
- [ ] Languages:
    - [x] Change languages
    - [x] Look for missing i18n
    - [x] Review language of i18n text strings 
- [ ] Modes:
    - [ ] Run all checks in RTL mode
    - [ ] Test in development mode
    - [ ] Online and offline
    - [ ] Mobile and desktop
    - [ ] Orange pi and Raspberry pi tests
    - [x] With different hostname <—*
    - [x] Flash to a card and test first boot 
- [ ] Settings
    - [ ] Database migrations
    - [x] Check routes are secured by jwt 
    - [x] Reset database even when it is corrupted 
    - [x] Change hostname and wifi ssid ***** <—
    - [x] Prune files
    - [x] Portainer URL with differ by hostname *
    - [x] Enable/disable portainer, and prune images *
    - [x] System info accurate
    - [x] Login
    - [x] Logout
    - [x] Set password
    - [x] Enable and disable components
    - [x] Set control panel password
    - [x] Set Custom start pages
- [x] File Manager
    - [x] USB
    - [x] Check on mobile and desktop as code is different. 
    - [x] Delete, within sub-directories, extract…
    - [x] File manager in admin mode when logged in
    - [x] Open from epub
    - [x] Auto file open feature —auto-open
    - [x] Change website files
    - [x] Create new folder
    - [x] Filter

- [x] Library
    - [x] Edit library content from settings panel
    - [x] Open from library
    - [x] Download from Library ***

- [ ] App Store 
    - [ ] Update app via App Store and then trigger update from control panel
    - [ ] Password for bookstack login works
    - [x] Delete an app
    - [x] Access an app
    - [x] Install all apps
    - [x] Refresh button should not be available when offline 

- [x] Find why App Store app names on mobile are short and and not long namr
- [x] Add spacing to wifi connect button logo
- [x] Change system maintained logo to yellow 
- [x] Remove space from below System Info heading 
- [x] Check epubs scale on new build and display on mobile
- [x] Test wifi is coming up with new name including ‘
