### ISSUE TITLE
Github releases action should update version.env file 

### ISSUE THREAD

**Issue by maximilianoertel** [LearnersBlock/learners-block#4]
Build process should output a `version.env` file containing the current version number which will be read from the controller. 

More about this can be read within ticket LearnersBlock/interface#3

**Comment by maggie0002** [comment]
Endpoint is now the same, but will only return one entry: 'lb_version': '0.0.1',.

The version is set in controller/.env

**Comment by maggie0002** [comment]
Added to workflows
