### ISSUE TITLE
Remove repeated JSON language entries

### ISSUE THREAD

**Issue by maggie0002** [LearnersBlock/learners-block#58]
Can we use the 'general' section more of the JSON language file. For example, at the moment the word 'close' is being translated 8 times for each language, would be easier for translation to have it done once in the general section. Same for other repetitive strings.  

https://github.com/LearnersBlock/learners-block/blob/22897e1b06e31570aaf0f77fcc61948a7e3e32f1/frontend/apps/interface/src/lang/en.json#L161

**Comment by maggie0002** [comment]
Submit the change to the l10n_master branch though, and will merge it later (due to some Weblate issues).

**Comment by maximilianoertel** [comment]
I can do that, no problem. 

Just for my curiosity: why did we need a `l10n_master` branch? Does Weblate do something weird?

**Comment by maggie0002** [comment]
Forget the last message, managed to bring the two branches in line so can make changes directly to Master.

l10n_master is created automatically by Weblate when changes are made in the web app, so that they are not pushed straight to Master.
