### ISSUE TITLE
Update File Manager auth endpoints and language setting

### ISSUE THREAD

**Issue by maggie0002** [LearnersBlock/learners-block#90]
There is a cookie stored on login with a JWT Token and some new endpoints on Controller for authentication. Goal here is to get File Manager to point to it and use it for auth as a new backend. At the moment the token is both in local storage and session storage. 

There is also a cookie called lang that will appear when someone sets the language for the interface. Looking to have File Manager read from that to dictate the language too. Note that default language is en-us now, rather than 'en'. Would be good for it to treat the two as the same.

Auth routes (although realise that not all will be needed for this) are:

    '/v1/login'
    '/v1/logout'
    '/v1/setpassword'
    '/v1/verifylogin'

Related to: https://github.com/LearnersBlock/learners-block/issues/73
Related to: https://github.com/LearnersBlock/learners-block/issues/7

**Comment by maggie0002** [comment]
When following URL, FileManager will need to open folder:

Settings panel:

/files  =  /app/web/public/storage/
/website  =   /app/web/public/storage/website

User interface:

/files  =  /app/web/public/storage/fileshare
/library = /app/web/public/storage/library 
/makerspace = /app/web/public/storage/makerspace

**Comment by maximilianoertel** [comment]
@maggie0002 just to be sure I entirely understand what you're trying to achieve, can you please confirm the points below for me? 

1) `/files`, `upload-website`, `/library` and `/makerspace` should all point to the file manager but load a different file root directory based on the URL and whether or not you're accessing those as an authenticated admin, correct? 

2) Have you already configured NGINX to handle the routing or does this still needs to be done as part of this ticket?

**Comment by maggie0002** [comment]
1. Yes
2. NGINX file already has those routes in it.
